version: '3.8'

services:
  db:
    image: postgres:15
    container_name: bank_postgres
    environment:
      POSTGRES_DB: bankdb
      POSTGRES_USER: bankuser
      POSTGRES_PASSWORD: bankpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bank_network
    restart: unless-stopped

  app:
    build: .
    container_name: bank_app
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/bankdb
      SPRING_DATASOURCE_USERNAME: bankuser
      SPRING_DATASOURCE_PASSWORD: bankpass
    depends_on:
      - db
    networks:
      - bank_network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  bank_network:
    driver: bridge
